### ISSUE TITLE
PLATEAU accepted proposal 11: Source for paragraphs / 段落内の出典

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#77]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
JISの規則では認められていないが、metanormaでは可能。→JIS 規則の採用を推奨

PLATEAU note: 
JIS does not support paragraph sources. There is no need for paragraph sources.

**Comment by opoudjis** [comment]
I'm now confused. I implemented sources on paragraphs and lists, as requested in https://github.com/metanorma/metanorma-plateau/issues/51 . https://github.com/metanorma/metanorma-plateau/issues/78 , read in the light of this (because JIS indeed do not have paragraph sources) seems to say that the functionality is not desired after all, and that "If not, we edit it directly in adoc file" actually means inline referencing, not a separate source.

An explanation of what is being requested, that is internally consistent, is needed.

**Comment by opoudjis** [comment]
Keeping the paragraph and list sources functionality just in case.

**Comment by ronaldtse** [comment]
We should keep the functionality for:
* paragraph sources
* list sources

It's just that PLATEAU users won't be using them.
