### ISSUE TITLE
PLATEAU accepted proposal 16: "Pay attention" items / 留意事項	

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plateau#82]
From: https://github.com/metanorma/metanorma-plateau/issues/64

Our proposal is accepted:
1，この要素にコンテナを設け、読者がどこで終わるか分かるようにする。2，附属書を含め、文書全体で一意に番号を付ける。URIを使った要求事項のような識別子を採用する。3，OGC ModSpec 要件モデルを採用する。OGC ModSpecは要件や 推奨を支持する。

PLATEAU note: 
- accept with note
- Adopt 2. We'd like to add a prefix for each identifier of "留意事項" to number them in each annex.

**Comment by opoudjis** [comment]
1 says:

> 1. Provide a container for this element so the reader knows where to end.

I assume that is referring to rendering, and typographically delimiting these identifiers. This is covered by the pending ticket https://github.com/metanorma/mn-samples-plateau/issues/119; I will paste here what the output looks like, now that Modspec has been adopted.

> We'd like to add a prefix for each identifier of "留意事項" to number them in each annex.

Is this referring to a table of recommendations? Or something else?

We had discussed introducing an "attention" type of recommendations, to deal with these (if we were not going to liberalise the obligation attribute.) I would suggest using just the generic classification tag, rather than attempting to extend the syntax outside of Modspec: 

````
classification:: subtype:attention
````

or

````
classification:: subtype:留意事項
````

**Comment by opoudjis** [comment]
Attention is a sibling of recommendation and requirement, and needs to be treated as such, as an obligation attribute.

**Comment by opoudjis** [comment]
Would want configurable labelling of provisions, to be extensible.

**Comment by opoudjis** [comment]
I initially thought that the solution to this was to introduce a separate level of obligation, "attention" alongside "permission, recommendation, requirement", and use that to label the provision.

But these are a separately numbered and labelled class of provision, and a provision can be separately numbered and labelled for any number of reasons, which may have nothing to do with obligation.

We have dealt with this kind of issue before. Diagrams, charts, and plates are all figures, and are all marked up in Metanorma as figures. But we allow them to be numbered and labelled separately, using the `class` attribute.

I will introduce that generically for requirements, as it should apply regardless of requirement model --- this is a Metanorma requirement. This will be a new `class` attribute on all requirements.

We could internationalise the class, but given that Plateau is not bilingual, it will suffice to introduce `class:: 留意事項` to the markup of Plateau provisions. While classes are not part of Modspec per se, they should be passed on to Modspec in Metanorma, as part of Metanorma's handling of provisions in general.

**Comment by opoudjis** [comment]
I'm adding `class:: 留意事項` to the Plateau document.
